# Generated by Django 4.2 on 2023-04-07 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetos',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.categorias', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='objetos',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Visto'),
        ),
        migrations.AddField(
            model_name='objetos',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripcion'),
        ),
    ]
