# Generated by Django 4.2 on 2023-04-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_objetos_categorie_objetos_date_objetos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetos',
            name='description',
            field=models.TextField(default=False, verbose_name='Descripcion'),
        ),
    ]
