# Generated by Django 4.2 on 2023-04-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_objetos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetos',
            name='description',
            field=models.TextField(default=True, verbose_name='Descripcion'),
        ),
    ]
