# Generated by Django 4.2 on 2023-04-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_objetos_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='objetos',
            new_name='Datos',
        ),
    ]
