# Generated by Django 4.2 on 2023-04-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_rename_objetos_datos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='date',
        ),
        migrations.AlterField(
            model_name='datos',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.categorias', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='done',
            field=models.BooleanField(verbose_name='Visto'),
        ),
    ]
