# Generated by Django 4.2 on 2023-04-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_remove_datos_date_alter_datos_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='datos',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Visto'),
        ),
    ]
