# Generated by Django 4.2 on 2023-04-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_ver_alter_datos_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='uptadet',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Hecho'),
        ),
    ]
