# Generated by Django 4.2 on 2023-04-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_datos_created_datos_uptadet_alter_datos_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos',
            options={'ordering': ['-uptadet', '-created']},
        ),
    ]
