# Generated by Django 4.2 on 2023-04-25 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0011_datos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
